### ISSUE TITLE
status field only on edit-deck & edit-card forms

### ISSUE THREAD

**Issue by findandrew** [eruditionapp/eruditionapp#32]
the `status` field for `decks` should not appear on create deck forms
<img width="532" alt="screen shot 2016-04-11 at 8 46 48 pm" src="https://cloud.githubusercontent.com/assets/1417199/14447620/06bf1246-0027-11e6-88d5-3dc1c9efc2dc.png">
it should, however, appear on edit deck forms
<img width="530" alt="screen shot 2016-04-11 at 8 47 12 pm" src="https://cloud.githubusercontent.com/assets/1417199/14447622/0fa85642-0027-11e6-9fa9-105a05ecf848.png">
this is because a newly created deck defaults to `status: unpublished` and it is required that a superadmin manually set it to `published` later. if we allow new decks to be created with `status: published` then there will likely be a period of time that a new deck is published with no cards

**Comment by findandrew** [comment]
the same pattern applies to card forms. (or does it make sense to keep them on card creation forms?)
<img width="730" alt="screen shot 2016-04-11 at 8 59 27 pm" src="https://cloud.githubusercontent.com/assets/1417199/14448835/276cda36-0032-11e6-992f-346518698539.png">

**Comment by cstillitano** [comment]
makes sense. lets remove `status` from new cards as well, for now
