### ISSUE TITLE
move deck preview out of learn mode

### ISSUE THREAD

**Issue by findandrew** [eruditionapp/eruditionapp#48]
notice the URL, the deck preview should probably not be a view in learn mode. learn mode should be reserved for the view/s in which the user is actually reading/answering prompts

<img width="831" alt="screen shot 2016-05-28 at 11 49 50 am" src="https://cloud.githubusercontent.com/assets/1417199/15628599/7e2ae4b4-24ca-11e6-845d-d439f7132dfe.png">

**Comment by cstillitano** [comment]
Fixed in f49115f9277e5d5bd2d0b3085b87f2d6d21fc9de, moved deck preview to `/users` directory
