### ISSUE TITLE
clean up static content

### ISSUE THREAD

**Issue by findandrew** [eruditionapp/eruditionapp#58]
details: https://eruditionapp.slack.com/archives/D0DS6L0AD/p1464571516000008

also the links in the footer all direct to `/#`, these should be removed and replaced with some one-liner / copyright / etc. OR updated to link to their appropriate pages

**Comment by cstillitano** [comment]
**Items removed:**
`/views/users/show`
- current decks
- title/author filters
- deck thumbnail
- deck difficulty
- deck progress bar
- deck preview

`/views/decks/show/`
- author table column

`/views/decks/_single_deck_summary`
- 'created at' in deck summary

`/views/cards/edit`
- 'reviewed by' in card summary

`/views/cards/_card`
- card author

`/views/shared/_footer`
- contact
- jobs

`assets/stylesheets/components/_grid`
- block thumbnail
- block difficulty
- block progress bar
- block popover

`assets/images/temp/`
- deck thumbnail images
